export default {
    SET_TABLE_LIST: 'SET_TABLE_LIST',
    SET_PAGE_SIZE: 'SET_PAGE_SIZE',
    SET_TOTAL: 'SET_TOTAL',
    SET_PAGE: 'SET_PAGE',
    RESET_SEARCH_RESULT: 'RESET_SEARCH_RESULT',
    TABLE_LOADING: 'TABLE_LOADING',
    COMMON_TABLE_MUTATE: 'COMMON_TABLE_MUTATE',
    SET_TABLE_FINISHED: 'SET_TABLE_FINISHED',
    SET_REQUEST_FINISHED: 'SET_REQUEST_FINISHED'
};
